<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Hot sopt test sanity suite" duration-ms="104490" started-at="2019-09-19T21:27:56Z" finished-at="2019-09-19T21:29:40Z">
    <groups>
    </groups>
    <test name="Hot spot sanity test" duration-ms="104490" started-at="2019-09-19T21:27:56Z" finished-at="2019-09-19T21:29:40Z">
      <class name="com.qa.hotpot.tests.LoginTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.hotpot.tests.LoginTest@75201592]" name="setUp" is-config="true" duration-ms="9034" started-at="2019-09-19T21:27:56Z" finished-at="2019-09-19T21:28:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginTest()[pri:1, instance:com.qa.hotpot.tests.LoginTest@75201592]" name="loginTest" duration-ms="8559" started-at="2019-09-19T21:28:05Z" description="login testnwith correct username and password" finished-at="2019-09-19T21:28:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.hotpot.tests.LoginTest@75201592]" name="tearDown" is-config="true" duration-ms="1255" started-at="2019-09-19T21:28:14Z" finished-at="2019-09-19T21:28:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.hotpot.tests.LoginTest@75201592]" name="setUp" is-config="true" duration-ms="7133" started-at="2019-09-19T21:28:38Z" finished-at="2019-09-19T21:28:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="loginPageTitleTest()[pri:2, instance:com.qa.hotpot.tests.LoginTest@75201592]" name="loginPageTitleTest" duration-ms="5291" started-at="2019-09-19T21:28:45Z" description="login page title test" finished-at="2019-09-19T21:28:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.hotpot.tests.LoginTest@75201592]" name="tearDown" is-config="true" duration-ms="1770" started-at="2019-09-19T21:28:51Z" finished-at="2019-09-19T21:28:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.hotpot.tests.LoginTest -->
      <class name="com.qa.hotpot.tests.HomePageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.hotpot.tests.HomePageTest@7726e185]" name="setUp" is-config="true" duration-ms="21439" started-at="2019-09-19T21:28:15Z" finished-at="2019-09-19T21:28:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyHomePageTitleTest()[pri:1, instance:com.qa.hotpot.tests.HomePageTest@7726e185]" name="verifyHomePageTitleTest" duration-ms="99" started-at="2019-09-19T21:28:37Z" finished-at="2019-09-19T21:28:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomePageTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.hotpot.tests.HomePageTest@7726e185]" name="tearDown" is-config="true" duration-ms="1312" started-at="2019-09-19T21:28:37Z" finished-at="2019-09-19T21:28:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.hotpot.tests.HomePageTest@7726e185]" name="setUp" is-config="true" duration-ms="22220" started-at="2019-09-19T21:28:53Z" finished-at="2019-09-19T21:29:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyHomePageHeaderTest()[pri:2, instance:com.qa.hotpot.tests.HomePageTest@7726e185]" name="verifyHomePageHeaderTest" duration-ms="675" started-at="2019-09-19T21:29:15Z" finished-at="2019-09-19T21:29:16Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Set up your HubSpot account] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Set up your HubSpot account] but found []
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.qa.hotpot.tests.HomePageTest.verifyHomePageHeaderTest(HomePageTest.java:42)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomePageHeaderTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.hotpot.tests.HomePageTest@7726e185]" name="tearDown" is-config="true" duration-ms="1319" started-at="2019-09-19T21:29:16Z" finished-at="2019-09-19T21:29:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.qa.hotpot.tests.HomePageTest@7726e185]" name="setUp" is-config="true" duration-ms="21404" started-at="2019-09-19T21:29:17Z" finished-at="2019-09-19T21:29:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyLoggedInUserAccountTest()[pri:3, instance:com.qa.hotpot.tests.HomePageTest@7726e185]" name="verifyLoggedInUserAccountTest" duration-ms="631" started-at="2019-09-19T21:29:38Z" finished-at="2019-09-19T21:29:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.qa.hotpot.tests.HomePageTest.verifyLoggedInUserAccountTest(HomePageTest.java:49)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoggedInUserAccountTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.hotpot.tests.HomePageTest@7726e185]" name="tearDown" is-config="true" duration-ms="1339" started-at="2019-09-19T21:29:39Z" finished-at="2019-09-19T21:29:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.hotpot.tests.HomePageTest -->
    </test> <!-- Hot spot sanity test -->
  </suite> <!-- Hot sopt test sanity suite -->
</testng-results>
